// WHO-recommended vaccination schedules by country
// Reference: WHO Vaccine Preventable Diseases Monitoring System

export interface VaccineScheduleItem {
  vaccineName: string;
  vaccineCode: string;
  doseNumber: number;
  ageInDays: number;
  ageDescription: string;
  mandatory: boolean;
  description: string;
  sideEffects: string;
}

// Universal WHO schedule (default for most countries)
export const whoSchedule: VaccineScheduleItem[] = [
  // Birth vaccines
  {
    vaccineName: "Hepatitis B",
    vaccineCode: "HepB",
    doseNumber: 1,
    ageInDays: 0,
    ageDescription: "Birth",
    mandatory: true,
    description: "First dose of Hepatitis B vaccine to protect against liver infection",
    sideEffects: "Mild fever, soreness at injection site",
  },
  {
    vaccineName: "BCG (Tuberculosis)",
    vaccineCode: "BCG",
    doseNumber: 1,
    ageInDays: 0,
    ageDescription: "Birth",
    mandatory: true,
    description: "Protection against tuberculosis",
    sideEffects: "Small bump at injection site that may become a small scar",
  },
  {
    vaccineName: "Oral Polio Vaccine",
    vaccineCode: "OPV",
    doseNumber: 0,
    ageInDays: 0,
    ageDescription: "Birth",
    mandatory: true,
    description: "Birth dose of oral polio vaccine",
    sideEffects: "Rarely causes any side effects",
  },
  
  // 6 weeks vaccines
  {
    vaccineName: "DTP (Diphtheria, Tetanus, Pertussis)",
    vaccineCode: "DTP",
    doseNumber: 1,
    ageInDays: 42,
    ageDescription: "6 weeks",
    mandatory: true,
    description: "First dose of combined vaccine against diphtheria, tetanus, and whooping cough",
    sideEffects: "Fever, fussiness, soreness at injection site",
  },
  {
    vaccineName: "Hepatitis B",
    vaccineCode: "HepB",
    doseNumber: 2,
    ageInDays: 42,
    ageDescription: "6 weeks",
    mandatory: true,
    description: "Second dose of Hepatitis B vaccine",
    sideEffects: "Mild fever, soreness at injection site",
  },
  {
    vaccineName: "Haemophilus influenzae type b",
    vaccineCode: "Hib",
    doseNumber: 1,
    ageInDays: 42,
    ageDescription: "6 weeks",
    mandatory: true,
    description: "Protection against Hib diseases including meningitis",
    sideEffects: "Redness at injection site, mild fever",
  },
  {
    vaccineName: "Pneumococcal Conjugate Vaccine",
    vaccineCode: "PCV",
    doseNumber: 1,
    ageInDays: 42,
    ageDescription: "6 weeks",
    mandatory: true,
    description: "Protection against pneumococcal diseases",
    sideEffects: "Drowsiness, decreased appetite, mild fever",
  },
  {
    vaccineName: "Rotavirus",
    vaccineCode: "RV",
    doseNumber: 1,
    ageInDays: 42,
    ageDescription: "6 weeks",
    mandatory: true,
    description: "Protection against rotavirus gastroenteritis",
    sideEffects: "Mild diarrhea, irritability",
  },
  {
    vaccineName: "Oral Polio Vaccine",
    vaccineCode: "OPV",
    doseNumber: 1,
    ageInDays: 42,
    ageDescription: "6 weeks",
    mandatory: true,
    description: "First primary dose of oral polio vaccine",
    sideEffects: "Rarely causes any side effects",
  },

  // 10 weeks vaccines
  {
    vaccineName: "DTP (Diphtheria, Tetanus, Pertussis)",
    vaccineCode: "DTP",
    doseNumber: 2,
    ageInDays: 70,
    ageDescription: "10 weeks",
    mandatory: true,
    description: "Second dose of DTP vaccine",
    sideEffects: "Fever, fussiness, soreness at injection site",
  },
  {
    vaccineName: "Haemophilus influenzae type b",
    vaccineCode: "Hib",
    doseNumber: 2,
    ageInDays: 70,
    ageDescription: "10 weeks",
    mandatory: true,
    description: "Second dose of Hib vaccine",
    sideEffects: "Redness at injection site, mild fever",
  },
  {
    vaccineName: "Pneumococcal Conjugate Vaccine",
    vaccineCode: "PCV",
    doseNumber: 2,
    ageInDays: 70,
    ageDescription: "10 weeks",
    mandatory: true,
    description: "Second dose of PCV",
    sideEffects: "Drowsiness, decreased appetite, mild fever",
  },
  {
    vaccineName: "Rotavirus",
    vaccineCode: "RV",
    doseNumber: 2,
    ageInDays: 70,
    ageDescription: "10 weeks",
    mandatory: true,
    description: "Second dose of rotavirus vaccine",
    sideEffects: "Mild diarrhea, irritability",
  },
  {
    vaccineName: "Oral Polio Vaccine",
    vaccineCode: "OPV",
    doseNumber: 2,
    ageInDays: 70,
    ageDescription: "10 weeks",
    mandatory: true,
    description: "Second primary dose of oral polio vaccine",
    sideEffects: "Rarely causes any side effects",
  },

  // 14 weeks vaccines
  {
    vaccineName: "DTP (Diphtheria, Tetanus, Pertussis)",
    vaccineCode: "DTP",
    doseNumber: 3,
    ageInDays: 98,
    ageDescription: "14 weeks",
    mandatory: true,
    description: "Third dose of DTP vaccine",
    sideEffects: "Fever, fussiness, soreness at injection site",
  },
  {
    vaccineName: "Hepatitis B",
    vaccineCode: "HepB",
    doseNumber: 3,
    ageInDays: 98,
    ageDescription: "14 weeks",
    mandatory: true,
    description: "Third dose of Hepatitis B vaccine",
    sideEffects: "Mild fever, soreness at injection site",
  },
  {
    vaccineName: "Haemophilus influenzae type b",
    vaccineCode: "Hib",
    doseNumber: 3,
    ageInDays: 98,
    ageDescription: "14 weeks",
    mandatory: true,
    description: "Third dose of Hib vaccine",
    sideEffects: "Redness at injection site, mild fever",
  },
  {
    vaccineName: "Pneumococcal Conjugate Vaccine",
    vaccineCode: "PCV",
    doseNumber: 3,
    ageInDays: 98,
    ageDescription: "14 weeks",
    mandatory: true,
    description: "Third dose of PCV",
    sideEffects: "Drowsiness, decreased appetite, mild fever",
  },
  {
    vaccineName: "Inactivated Polio Vaccine",
    vaccineCode: "IPV",
    doseNumber: 1,
    ageInDays: 98,
    ageDescription: "14 weeks",
    mandatory: true,
    description: "First dose of inactivated polio vaccine",
    sideEffects: "Soreness at injection site",
  },
  {
    vaccineName: "Oral Polio Vaccine",
    vaccineCode: "OPV",
    doseNumber: 3,
    ageInDays: 98,
    ageDescription: "14 weeks",
    mandatory: true,
    description: "Third primary dose of oral polio vaccine",
    sideEffects: "Rarely causes any side effects",
  },

  // 9 months vaccines
  {
    vaccineName: "Measles, Mumps, Rubella",
    vaccineCode: "MMR",
    doseNumber: 1,
    ageInDays: 270,
    ageDescription: "9 months",
    mandatory: true,
    description: "First dose of MMR vaccine",
    sideEffects: "Mild fever, rash 7-12 days after vaccination",
  },
  {
    vaccineName: "Yellow Fever",
    vaccineCode: "YF",
    doseNumber: 1,
    ageInDays: 270,
    ageDescription: "9 months",
    mandatory: false,
    description: "Yellow fever vaccine (required in endemic areas)",
    sideEffects: "Headache, muscle aches, mild fever",
  },

  // 12-15 months vaccines
  {
    vaccineName: "Measles, Mumps, Rubella",
    vaccineCode: "MMR",
    doseNumber: 2,
    ageInDays: 365,
    ageDescription: "12 months",
    mandatory: true,
    description: "Second dose of MMR vaccine",
    sideEffects: "Mild fever, rash",
  },
  {
    vaccineName: "Varicella (Chickenpox)",
    vaccineCode: "VAR",
    doseNumber: 1,
    ageInDays: 365,
    ageDescription: "12 months",
    mandatory: true,
    description: "First dose of chickenpox vaccine",
    sideEffects: "Soreness at injection site, mild fever, mild rash",
  },
  {
    vaccineName: "Hepatitis A",
    vaccineCode: "HepA",
    doseNumber: 1,
    ageInDays: 365,
    ageDescription: "12 months",
    mandatory: false,
    description: "First dose of Hepatitis A vaccine",
    sideEffects: "Soreness at injection site, headache",
  },

  // 18 months vaccines
  {
    vaccineName: "DTP (Diphtheria, Tetanus, Pertussis)",
    vaccineCode: "DTP",
    doseNumber: 4,
    ageInDays: 548,
    ageDescription: "18 months",
    mandatory: true,
    description: "Fourth dose (booster) of DTP vaccine",
    sideEffects: "Fever, fussiness, soreness at injection site",
  },
  {
    vaccineName: "Hepatitis A",
    vaccineCode: "HepA",
    doseNumber: 2,
    ageInDays: 548,
    ageDescription: "18 months",
    mandatory: false,
    description: "Second dose of Hepatitis A vaccine",
    sideEffects: "Soreness at injection site, headache",
  },

  // 4-6 years vaccines
  {
    vaccineName: "DTP (Diphtheria, Tetanus, Pertussis)",
    vaccineCode: "DTP",
    doseNumber: 5,
    ageInDays: 1825,
    ageDescription: "5 years",
    mandatory: true,
    description: "Fifth dose (booster) of DTP vaccine before school entry",
    sideEffects: "Fever, fussiness, soreness at injection site",
  },
  {
    vaccineName: "Oral Polio Vaccine",
    vaccineCode: "OPV",
    doseNumber: 4,
    ageInDays: 1825,
    ageDescription: "5 years",
    mandatory: true,
    description: "Booster dose of oral polio vaccine",
    sideEffects: "Rarely causes any side effects",
  },
  {
    vaccineName: "Varicella (Chickenpox)",
    vaccineCode: "VAR",
    doseNumber: 2,
    ageInDays: 1825,
    ageDescription: "5 years",
    mandatory: true,
    description: "Second dose of chickenpox vaccine",
    sideEffects: "Soreness at injection site, mild fever",
  },
];

// Country-specific schedules (variations from WHO)
export const countrySchedules: Record<string, VaccineScheduleItem[]> = {
  "United States": [
    ...whoSchedule,
    {
      vaccineName: "HPV (Human Papillomavirus)",
      vaccineCode: "HPV",
      doseNumber: 1,
      ageInDays: 4015,
      ageDescription: "11 years",
      mandatory: false,
      description: "First dose of HPV vaccine",
      sideEffects: "Pain at injection site, headache, fever",
    },
    {
      vaccineName: "HPV (Human Papillomavirus)",
      vaccineCode: "HPV",
      doseNumber: 2,
      ageInDays: 4197,
      ageDescription: "11.5 years",
      mandatory: false,
      description: "Second dose of HPV vaccine",
      sideEffects: "Pain at injection site, headache, fever",
    },
    {
      vaccineName: "Meningococcal",
      vaccineCode: "MCV",
      doseNumber: 1,
      ageInDays: 4015,
      ageDescription: "11 years",
      mandatory: true,
      description: "First dose of meningococcal vaccine",
      sideEffects: "Redness at injection site, headache, fatigue",
    },
    {
      vaccineName: "Tdap (Tetanus, Diphtheria, Pertussis)",
      vaccineCode: "Tdap",
      doseNumber: 1,
      ageInDays: 4015,
      ageDescription: "11 years",
      mandatory: true,
      description: "Adolescent booster for tetanus, diphtheria, and pertussis",
      sideEffects: "Pain at injection site, headache, fatigue",
    },
  ],
  "United Kingdom": whoSchedule,
  "India": whoSchedule,
  "Germany": whoSchedule,
  "France": whoSchedule,
  "Brazil": whoSchedule,
  "Japan": whoSchedule,
  "Australia": whoSchedule,
  "Canada": whoSchedule,
  "South Africa": whoSchedule,
  "Nigeria": whoSchedule,
  "Mexico": whoSchedule,
  "Indonesia": whoSchedule,
  "Pakistan": whoSchedule,
  "Bangladesh": whoSchedule,
  "Philippines": whoSchedule,
  "Vietnam": whoSchedule,
  "Egypt": whoSchedule,
  "Turkey": whoSchedule,
  "Iran": whoSchedule,
  "Thailand": whoSchedule,
  "Kenya": whoSchedule,
  "Colombia": whoSchedule,
  "Argentina": whoSchedule,
  "Spain": whoSchedule,
  "Italy": whoSchedule,
  "Poland": whoSchedule,
  "Saudi Arabia": whoSchedule,
  "United Arab Emirates": whoSchedule,
  "Malaysia": whoSchedule,
  "Singapore": whoSchedule,
};

export function getScheduleForCountry(country: string): VaccineScheduleItem[] {
  return countrySchedules[country] || whoSchedule;
}

// List of supported countries
export const supportedCountries = [
  "Afghanistan", "Albania", "Algeria", "Argentina", "Australia", "Austria",
  "Bangladesh", "Belgium", "Brazil", "Canada", "Chile", "China", "Colombia",
  "Czech Republic", "Denmark", "Egypt", "Ethiopia", "Finland", "France",
  "Germany", "Ghana", "Greece", "Hungary", "India", "Indonesia", "Iran",
  "Iraq", "Ireland", "Israel", "Italy", "Japan", "Jordan", "Kazakhstan",
  "Kenya", "Kuwait", "Lebanon", "Malaysia", "Mexico", "Morocco", "Myanmar",
  "Nepal", "Netherlands", "New Zealand", "Nigeria", "Norway", "Pakistan",
  "Peru", "Philippines", "Poland", "Portugal", "Qatar", "Romania", "Russia",
  "Saudi Arabia", "Singapore", "South Africa", "South Korea", "Spain",
  "Sri Lanka", "Sudan", "Sweden", "Switzerland", "Syria", "Taiwan",
  "Tanzania", "Thailand", "Tunisia", "Turkey", "Uganda", "Ukraine",
  "United Arab Emirates", "United Kingdom", "United States", "Venezuela",
  "Vietnam", "Yemen", "Zimbabwe"
].sort();
